# Generated by Django 4.2.1 on 2023-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
