# Generated by Django 4.2.1 on 2023-05-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_lista_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
