# Generated by Django 4.2.1 on 2023-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_lista_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='useratribuido',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
