# Generated by Django 4.2.1 on 2023-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_lista_useratribuido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='dataatribuicao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lista',
            name='datafinalizacao',
            field=models.DateTimeField(),
        ),
    ]
