# Generated by Django 4.2.1 on 2023-05-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_alter_lista_dataatribuicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='concluido',
            field=models.BooleanField(),
        ),
    ]
